# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 100
  - name: About
    url: about/
    weight: 200
  - name: Contact
    url: contact/
    weight: 300
  - name: Map
    parent: Contact
    url: map/
    weight: 310
  - name: Phone
    parent: Contact
    url: phone/
    weight: 320
  - name: Information
    url: information/
    weight: 400
  - name: Event
    url: event/
    weight: 500